### ISSUE TITLE
Wat is de ketel aan het doen?

### ISSUE THREAD

**Issue by FutureCow** [kozmoz/atag-one-api#15]
Als eerste bedankt voor dit prachtige stukje software. Alles wordt netjes in een database gezet, en krijg daar prachtige grafieken mee! erg handig om de boel een beetje in de gaten te houden. (En alles naar OpenHAB te sturen)

Ik had even een vraag. Met welke parameter kan ik er achter komen of de ketel bezig is met CV of warmwater?

Bij Boilerstatus komen de waarden: 258, 260, 266 en 268 voorbij, kan ik daar iets mee?

**Comment by kozmoz** [comment]
Op de wiki pagina heb ik geprobeerd het protocol te beschrijven.

https://github.com/kozmoz/atag-one-api/wiki/Thermostat-Protocol 
Zie daar de variabele genaamd "report.boiler_status". Deze geeft inderdaad met bits aan wat de status van de brander is.

**Comment by Bergerie** [comment]
I'm puzzled. {$dump->retrieve_reply->report->boiler_status} geeft continue een waarde van slechts 127. Inconsistent met de variabelen welke zijn omschreven onder "report.boiler_status".

**Comment by kozmoz** [comment]
Welk commando voer je exact uit om de dump te ontvangen? Wat is de software versie van de Atag ONE? Mogelijk geven de antwoorden hierop een oplossingsrichting.

**Comment by Bergerie** [comment]
Hi Rob,

dank voor snelle reaktie.

Device Settings geeft aan "One version R46"

Commando is: $json = `java -jar $jar --skip-auth-request --dump`;

**Comment by kozmoz** [comment]
Firmware R46 is de laatste versie.

De dump zet de waarden van de Atag ONE één op één door. Dan zou ik verwachten dat het binnen de app ook niet goed weergegeven wordt. Wordt daar dan wel juist getoond dat de brander actief is?

"boiler_status": 778,

**Comment by Bergerie** [comment]
Hi Rob,

Excuses, foutje mijnerzijds. Ik kreeg constant een waarde van 127 in mijn sql database. Echter, bij wijziging van FieldType werd er ineens de waarden 512, 770, 778, 780 weggeschreven. Nu nog even uit zien te vinden waar die waarden voor staan.

Grtjs

Dick
