### ISSUE TITLE
Report time ligt een dag min een paar seconden in de toekomst

### ISSUE THREAD

**Issue by lennertcc** [kozmoz/atag-one-api#16]
Het is zaterdag 15-4-2017 20:05
Ik verbind **lokaal** op de Atag One, dus de report time is gelijk aan de system time. 

De dump rapporteert:

> { "retrieve_reply":{ "seqnr":0,"status":{"device_id":"6808-1500-1803_16-42-001-266","device_status":16385,"connection_status":7,"date_time":545594708},"report":{"report_time":545594708,"burning_hours":958.00......

diagnostics.get(AtagOneConnectorInterface.VALUE_LATEST_REPORT_TIME) rapporteert:

> 2017-04-16 20:05:02

epochconverter.com maakt van 545594708:

> GMT: Thu, 16 Apr 1987 18:05:08 GMT
> Your time zone: ‎16‎-‎4‎-‎1987‎ ‎20‎:‎05‎:‎08 GMT+2:00 DST
> 

Om de juiste tijd te krijgen doe ik:
```
        TimeZone timeZone = TimeZone.getDefault();
        int offset = timeZone.getOffset(System.currentTimeMillis());
        LocalDateTime ofEpoch = LocalDateTime.ofEpochSecond(545594708, 0, ZoneOffset.ofTotalSeconds(offset/1000));
        LocalDateTime reportTime = ofEpoch.plusYears(30).minusDays(1);

```
Dit geeft correct 2017-04-15T20:05:08

**Comment by kozmoz** [comment]
Hallo Lennert, bedankt voor je bug report. Grappig dat mij dit nog niet eerder opgevallen is. Ik ga het aanpassen in de code.

**Comment by ArdKuijpers** [comment]
Het lijkt er op dat ATAG de bug zelf gefixt heeft want nu wordt in de dump wel de goede datum gerapporteerd en dus geeft de huidige versie van atag-one.jar bij een **lokale** oproep een latestReportTime van een dag eerder atagOneVersion: R58. De **remote** oproep geeft wel de goede datum.

**Comment by kozmoz** [comment]
mijn vermoeden is dat dit te maken heeft met de omzetting die toch nog niet correct is. Via de Java Date methode komt er een datum uit die 30 jaar achter loopt. Nu wordt er 30 jaar bij opgeteld om bij de (schijnbaar) juiste datum uit te komen. Ik vermoed dat door schrikkeljaren er soms een dag verschil kan ontstaan.

De code is eenvoudig aan te passen, maar mogelijk loopt de datum volgend jaar dan weer een dag voor...

**Comment by lennertcc** [comment]
Misschien kan het opgelost worden door een basisdatum te nemen en daar de aantal seconden van de atag datum bij op te tellen. Dat is wezenlijk iets anders dan simpel 30 jaar toevoegen aan het date-object.

**Comment by ArdKuijpers** [comment]
@lennertcc Dat brengt ons op het juist spoor volens mij. Vandaag zag ik dat de latestReportTime een dag en een uur verschil had met de werkelijke tijd. Dus naast het probleem met schrikkeljaren is er ook nog een probleem met het ingaan van de zomertijd op verschillende dagen in verschillende jaren. 

De oplossing is de door de ATAG gerapporteerde dagen op te tellen bij het aantal seconden tussen 1-1-1970 en 1-1-2000. Daarmee lijkt het probleem opgelost. Ik heb het lokaal getest en het lijkt goed te werken. Bijgevoegd de aanpassingen (in een git diff, want ik ben nog niet zo thuis in GitHub pull requests). 

[fix-for-reportdate.diff.txt](https://github.com/kozmoz/atag-one-api/files/3010410/fix-for-reportdate.diff.txt)

**Comment by lennertcc** [comment]
Ja precies! En kun je de berekening eens loslaten op de tijden uit mijn allereerste post hierboven? Als dat ook goed uit komt dan is het bewijs volgens mij wel compleet.

**Comment by ArdKuijpers** [comment]
Kon het niet laten ;)
![image](https://user-images.githubusercontent.com/3098251/55035268-c751af80-5017-11e9-98c5-d0aff6f33357.png)

QED

**Comment by kozmoz** [comment]
Ha, toevallig was ik net ook met een oplossing bezig met hetzelfde resultaat. Oudere datums uit 2017 werken ook bij deze oplossing. Bij de datum uit 2015 krijg ik een dag verschil, maar wellicht is die datum nooit correct geweest... 

Ik ga de code aanpassen en een nieuwe versie releases. Dank voor het meedenken!

**Comment by kozmoz** [comment]
Nieuwe release! https://github.com/kozmoz/atag-one-api/releases/tag/v1.4.6
