### ISSUE TITLE
Remote API werkt niet

### ISSUE THREAD

**Issue by FutureCow** [kozmoz/atag-one-api#19]
Sinds een aantal dagen werkt de remote API bij mij niet meer. Is het iets wat bij mij niet goed is? Of hebben ze iets veranderd. Het hele jaar zonder problemen elke minuut uitgelezen. Dit krijg ik nu terug:

{
    "deviceId": "6808-1500-XXX_XX-XX-XXX-XXX",
    "deviceAlias": null,
    "latestReportTime": null,
    "connectedTo": null,
    "burningHours": null,
    "boilerHeatingFor": null,
    "flameStatus": null,
    "roomTemperature": null,
    "outsideTemperature": null,
    "dhwSetpoint": null,
    "dhwWaterTemperature": null,
    "chSetpoint": null,
    "chWaterTemperature": null,
    "chWaterPressure": null,
    "chReturnTemperature": null,
    "targetTemperature": 0,
    "currentMode": null,
    "vacationPlanned": null
}

**Comment by kozmoz** [comment]
En ja kan bevestigen dat inloggen met dezelfde inloggegevens op https://portal.atag-one.com/Account/Login?ReturnUrl=%2F nog wel correct werkt?

**Comment by FutureCow** [comment]
Yeps, dat had ik al getest
Met verkeerde inlog gegevens krijg ik ook netjes: Invalid username or password.

**Comment by kozmoz** [comment]
Had gehoopt dat als je daar een info window weg zou klikken het op magische wijze weer zou werken.

Bij mij werkt het trouwens nog wel gewoon. 

Wat het scriptje eigenlijk doet is de webpagina https://portal.atag-one.com/Device/Diagnostics/ uitlezen. Zie je wat raars op die pagina als je ingelogd bent bij Atag?

Is het misschien mogelijk om atag-one.jar lokaal te gebruiken, zodat het rechtstreeks contact maakt met de thermostaat? "$ java -jar atag-one.jar" in het lokale netwerk zou daarvoor voldoende moeten zijn.

**Comment by FutureCow** [comment]
Ah opgelost, ik kon op die pagina kiezen welke Atag One ik wilde bedienen(ik heb aan het begin een andere gekregen) Blijkbaar hebben ze iets aangepast aan de portal waardoor dit is veranderd.
Door de oude te verwijderen krijg ik weer de juiste gegevens binnen!

**Comment by kozmoz** [comment]
top! Houdt het script inderdaad geen rekening mee, meerdere thermostaten.

**Comment by FutureCow** [comment]
Bij mij loopt de Atag One nog wel 1 keer per dag vast. Dat zie ik alleen in mijn gegevens omdat ik dan 5 minuten geen update krijg. Merk er verder niets van. Dit had ik met de oude One, maar met de nieuwe ook. Merk daar iets van? (Ik log dus elke minuut)

**Comment by kozmoz** [comment]
Nee, nog niet ervaren. Misschien is op dat moment de verbinding even weg? Er zit geen timeout op het verbinding maken, de API blijft dan wachten totdat de gegevens binnenkomen
