### ISSUE TITLE
Modulation and other detailed information missing from --dump output

### ISSUE THREAD

**Issue by sanderplug** [kozmoz/atag-one-api#20]
I found out how retrieve_reply.report.details information can be made available. This sections contains modulation information (retrieve_reply.report.details.rel_mod_level) to show current modulation.

This can be retrieved by setting retrieve_message.info to 64 (report + details) or 255 (basically all available information and sections to be included in the --dump output).

`curl -H "Content-Type: application/json" -X POST -d '{ "retrieve_message": { "seqnr": 0, "account_auth": { "user_account": "", "mac_address": "<MAC>" }, "device_id": "6808-.......", "info": 64 } }' http://10.0.0.45:10000/retrieve`

Output for retrieve_message.info = 64
{ "retrieve_reply":{ "seqnr":0,"status":{"device_id":"6808-.......","device_status":16385,"connection_status":7,"date_time":560373413},"report":{"report_time":560373413,"burning_hours":0.20,"device_errors":"","boiler_errors":"","room_temp":20.6,"outside_temp":14.0,"dbg_outside_temp":22.1,"pcb_temp":25.1,"ch_setpoint":0.0,"dhw_water_temp":28.5,"ch_water_temp":20.6,"dhw_water_pres":0.0,"ch_water_pres":1.6,"ch_return_temp":20.6,"boiler_status":512,"boiler_config":772,"ch_time_to_temp":0,"shown_set_temp":15.0,"power_cons":0,"tout_avg":14.1,"rssi":36,"current":-80,"voltage":3896,"resets":3,"memory_allocation":2800, "details":{"boiler_temp":29.7,"boiler_return_temp":29.7,"dhw_flow_rate":0.0,"min_mod_level":21,**"rel_mod_level":0**,"boiler_capacity":0,"target_temp":15.0,"overshoot":0.000,"max_boiler_temp":85.0,"alpha_used":0.00083,"regulation_state":0,"ch_m_dot_c":0.000,"c_house":0,"r_rad":0.0000,"r_env":0.0000,"alpha":0.00000,"alpha_max":0.00083,"delay":1000,"mu":0.00,"threshold_offs":15.0,"wd_k_factor":1.6,"wd_exponent":1.2,"lmuc_burner_starts":15,"lmuc_burner_hours":0,"lmuc_dhw_hours":0,"KP":36.100,"KI":0.00568}},"acc_status":2} }

**Comment by kozmoz** [comment]
Interesting findings! Will add these details to the dump output soon

**Comment by at0rvk** [comment]
+1 looking forward to a new version

**Comment by Bergerie** [comment]
Any chance of an update soon to retrieve modulation level included in dump file?

**Comment by kozmoz** [comment]
Fresh new binary release which includes the modulation level info. Execute with the `--dump` flag to get the full output.

https://github.com/kozmoz/atag-one-api/releases/tag/v1.4.3
