### ISSUE TITLE
Add possibility to set "setpoint" temperature

### ISSUE THREAD

**Issue by kozmoz** [kozmoz/atag-one-api#21]
Add possibility to set "setpoint" temperature. 

The Atag ONE app can set the setpoint temperature, so it should be possible to with the API somehow.

**Comment by kozmoz** [comment]
"Ik bedoel overigens met de setpoint de maximale temperatuur die de ketel hanteert. 
Dat is het veld .configuration.ch_temp_max (https://github.com/kozmoz/atag-one-api/wiki/Thermostat-Protocol).
Die kun je instellen op de ketel en is normaal bij mijn ketel 85 graden.
 
De setpoint zelf wordt volgens mij (bij de weersafhankelijke regeling) door de ketel zelf bepaald. 
 
Ik wil het veld ch_temp_max graag via de api instellen."

**Comment by GingerAdonis** [comment]
Have you managed to look into this yet? :) It's one of the few things I can't change with the official app.

**Comment by kozmoz** [comment]
Just tested, didn't work unfortunately
