### ISSUE TITLE
Class cast exception

### ISSUE THREAD

**Issue by AndyKeogh** [kozmoz/atag-one-api#23]
Windows 10 v1703          java version 8 update 151

Following command did not work as expected.

C:\Users\Andrew\Downloads>java -jar atag-one.jar -o csv
java.lang.String cannot be cast to java.lang.Boolean

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
        at org.juurlink.atagone.AtagOneApp.main(AtagOneApp.java:109)

C:\Users\Andrew\Downloads>java -jar atag-one.jar -v
Version: 1.4.3
Build:  2017-11-06T08:12:57Z

**Comment by kozmoz** [comment]
Thanks for reporting! New version is live; should be fixed in 1.4.4
