### ISSUE TITLE
Change Request  time and date

### ISSUE THREAD

**Issue by AndyKeogh** [kozmoz/atag-one-api#26]
CSV format is extremely limited since the time and date are not included in the data output.

I want to build up 2 hours of samples every minute to ask ATAG  why my CH cycle starts 30 minutes late each day when the boiler has been doing nothing!!

Could you include time and date in CSV format?

Andy

**Comment by kozmoz** [comment]
$ java -jar atag-one.jar --dump

Dumps everything the thermostat knows. The format is json and a timestamp is included. Is parsing json an option?

**Comment by AndyKeogh** [comment]
Wow 254 columns when imported into excel.  I will select the columns of interest.
any clues on how to convert the following to readable format?

date_time:564345650}
--
report:{"report_time":564345650

Andy

**Comment by kozmoz** [comment]
Number of milliseconds sinds 2000.

This is the Java utility method that converts the value to a date:

public static LocalDateTime toDateObject(final long atagOneDate) {
    val timeZone = TimeZone.getDefault();
    val offset = timeZone.getOffset(atagOneDate * 1000);
    val ofEpoch = LocalDateTime.ofEpochSecond(atagOneDate, 0, ZoneOffset.ofTotalSeconds(offset / 1000));
    return ofEpoch.plusYears(30).minusDays(1);
}

**Comment by AndyKeogh** [comment]
Thanks for that.  Looks like it is actually seconds since 1st Jan 2000 as I have just decoded 564402174 to 19th November 2017 10:22:54 AM on that basis.

Andy
