### ISSUE TITLE
Differences in boiler_status replies (e.g. 524 vs 780)

### ISSUE THREAD

**Issue by MatsNl** [kozmoz/atag-one-api#28]
Hi!

First off, thanks for deciphering and documenting this beauty :)

I am trying to better understand the boiler_status in the json reply. Any idea what the differences are between the low 5xx values and high 7xx values? e.g. 524 and 780 are the same on 2, 4 and 8 operators, only difference is the additional 256. Both replies occur, but I don't think they both mean the same "heating for central heating", right..?

Any clues ? Could the 256 mean something additional?

Thanks!

**Comment by kozmoz** [comment]
Tried to find a clue in the Atag ONE app, but cannot find the meaning of the higher bits.

SO unfortunately I have no idea what these values represent

**Comment by MatsNl** [comment]
Searched a bit more as well, no success either.. 256 and 512 bits remain a mystery

**Comment by kozmoz** [comment]
I've updated the wiki page:
https://github.com/kozmoz/atag-one-api/wiki/Thermostat-Protocol

Added report.boiler_status &512 = dhw_schema and &256 = ch_schema.

> 256 staat voor ch_schema, oftewel of de centrale verwarming volgens schema op temperatuur gehouden wordt, of niet. 512 is voor dhw_schema, oftewel of je domestic hot water (warm water) volgens schema op temperatuur gehouden wordt.

Thanks to Gert Ouderkerken for providing this info
