### ISSUE TITLE
invalid response or no response

### ISSUE THREAD

**Issue by kevinramharak** [kozmoz/atag-one-api#29]
So i am trying to authenticate with the protocol described in the wiki and i am sending this:
```json
{
	"pair_message": {
		"seqnr": 1,
		"account_auth": {
			"user_account": "",
			"mac_address": "my_mac"
		},
		"accounts": {
			"entries": [
				{
					"user_account": "",
					"mac_address": "my_mac",
					"device_name": "dev_name",
					"account_type": 0
				}
			]
		}
	}
}
```
but:
- using Postman gets me no HTTP response . I can see some tcp traffic from the atag coming back, but that seems to be the tcp/ip layer
- using Curl i get the following response:
```json
{ "<invalid>":{ "seqnr":0,"acc_status":0} }
```

any tips or help? Id wanted to try here before reverse engineering the android app.

**Comment by kozmoz** [comment]
Hi Kevin,

https://github.com/kozmoz/atag-one-api/blob/master/src/main/java/org/juurlink/atagone/AtagOneLocalConnector.java <https://github.com/kozmoz/atag-one-api/blob/master/src/main/java/org/juurlink/atagone/AtagOneLocalConnector.java>
See the method requestAuthorizationFromThermostat(). But it looks already similar.

Sometimes you get an empty response. In my code I just try it a couple of times in that case.
Are you sure you send the right request headers for content type (application/json )and content length?

Good luck,
Rob
