### ISSUE TITLE
Outside temperature is unsigned what makes it incorrect when it's freezing

### ISSUE THREAD

**Issue by BertSchel** [kozmoz/atag-one-api#36]
Hi when I run the atag-one.jar file in my terminal, the output for "outsideTemperature" is currently 3.2, while the thermostat itself is showing -3,2. I looked at my graphs in grafana and I was surprised to see there has never been a negative temperature. Is there a possible fix for this? Thanks for the great repo by the way, very useful!

**Comment by kozmoz** [comment]
That's weird. In my current output is a negative "outsideTemperature": 

`% java -jar target/atag-one.jar`

Outputs: 
```json
{
    "deviceIP": "192.168.1.8",
    "deviceId": "6808-1401-3109_15-30-001-xxx",
    "latestReportTime": "2022-12-13 11:59:20",
    "burningHours": 9202.43,
    "roomTemperature": 20.0,
    "outsideTemperature": -2.1,
    "dhwSetpoint": 43.0,
    "dhwWaterTemperature": 56.6,
    "chSetpoint": 47.8,
    "chWaterTemperature": 55.5,
    "chWaterPressure": 1.7,
    "chReturnTemperature": 55.5,
    "targetTemperature": 20.0,
    "deviceStatus": 27649,
    "connectionStatus": 23,
    "deviceErrors": "",
    "boilerErrors": "",
    "dbgOutsideTemp": 22.1,
    "pcbTemp": 24.5,
    "dhwWaterTemp": 56.6,
    "dhwWaterPres": 0.0,
    "boilerStatus": 770,
    "boilerConfig": 772,
    "chTimeToTemp": 0,
    "powerCons": 659,
    "rssi": 26,
    "current": -97,
    "voltage": 3622,
    "resets": 0,
    "memoryAllocation": 2800,
    "chStatus": 45,
    "chControl_mode": 0,
    "chMode": 1,
    "chModeDuration": 0,
    "chModeTemp": 20.0,
    "dhwStatus": 45,
    "dhwMode": 1,
    "weatherTemp": -2.1,
    "weatherStatus": 0,
    "vacationDuration": 0,
    "extendDuration": 0,
    "fireplaceDuration": 10800,
    "flameStatus": "Off",
    "atagOneVersion": "R60",
    "macAddress": "F8-E4-3B-14-50-XX"
}
```

Can you double check your output of `% java -jar target/atag-one.jar`?

**Comment by BertSchel** [comment]
Hi @kozmoz. Sure can! Thermostat currently shows - 0,4 °C and this is the output of atag-one.jar:
{
    "deviceId": "xxxx-xxxx-xxxx_xx-xx-xxx-xxx",
    "deviceAlias": null,
    "latestReportTime": "2022-12-13 14:18:30",
    "connectedTo": null,
    "burningHours": 8125.07,
    "boilerHeatingFor": "CV",
    "flameStatus": "On",
    "roomTemperature": 21.1,
    "outsideTemperature": 0.4,
    "dhwSetpoint": 60.0,
    "dhwWaterTemperature": 50.6,
    "chSetpoint": 46.6,
    "chWaterTemperature": 53.3,
    "chWaterPressure": 1.9,
    "chReturnTemperature": 47.7,
    "targetTemperature": 21.0,
    "currentMode": "schedule_active",
    "vacationPlanned": false
}

Maybe worth to mention: I use the remote mode.

**Comment by BertSchel** [comment]
Found out that the results of the local and the remote mode are different. 
The local mode indeed shows a negative value but the remote mode leaves it unsigned. The reason why I used the remote mode is that the server where I collect the data on is on a different network than the ATAG-ONE thermostat.

This is the output of the local mode:

{
    "deviceIP": "xxx.xxx.x.xxx",
    "deviceId": "xxxx-xxxx-xxxx_xx-xx-xxx-xxx",
    "latestReportTime": "2022-12-13 15:42:39",
    "burningHours": 8126.54,
    "roomTemperature": 21.1,
    "outsideTemperature": -0.4,
    "dhwSetpoint": 60.0,
    "dhwWaterTemperature": 50.5,
    "chSetpoint": 44.3,
    "chWaterTemperature": 53.0,
    "chWaterPressure": 1.9,
    "chReturnTemperature": 47.2,
    "targetTemperature": 21.0,
    "deviceStatus": 16385,
    "connectionStatus": 23,
    "deviceErrors": "",
    "boilerErrors": "",
    "dbgOutsideTemp": 24.2,
    "pcbTemp": 27.4,
    "dhwWaterTemp": 50.5,
    "dhwWaterPres": 0.0,
    "boilerStatus": 778,
    "boilerConfig": 772,
    "chTimeToTemp": 0,
    "powerCons": 6599,
    "rssi": 36,
    "current": 44,
    "voltage": 3872,
    "resets": 14,
    "memoryAllocation": 14416,
    "chStatus": 189,
    "chControl_mode": 0,
    "chMode": 2,
    "chModeDuration": 0,
    "chModeTemp": 21.0,
    "dhwStatus": 45,
    "dhwMode": 1,
    "weatherTemp": -0.4,
    "weatherStatus": 8,
    "vacationDuration": 0,
    "extendDuration": 0,
    "fireplaceDuration": 10800,
    "flameStatus": "On",
    "atagOneVersion": "R60",
    "macAddress": "xx-xx-xx-xx-xx-xx"
}

**Comment by kozmoz** [comment]
Ah okay, probably easy to fix. Have to wait till it starts freezing again, will fix tonight ;-)

**Comment by BertSchel** [comment]
Nice, thank you!

**Comment by BertSchel** [comment]
@kozmoz I see it's already freezing in the Netherlands, that was solved really fast. Works like a charm, thanks for this!
