### ISSUE TITLE
Report.power_cons

### ISSUE THREAD

**Issue by kdtcat** [kozmoz/atag-one-api#37]
I try to find out which units are used for the status "report.power_cons". Any idea? Please ignore if you think this is not the write place to ask.

**Comment by kozmoz** [comment]
Good question. Never looked into "power_cons". 

Looks like It's the active gas usage; the current gas flow.

Compared to the gas usage in the graph below (that graph the volume is in liters) it looks like the unit for "power_cons" is **deciliter per hour**?

![](https://juur.link/download/gas-flow.png)

**Comment by kdtcat** [comment]
Well, you might be right with your assumption. My graph for the power consumption looks similar. 
![image](https://user-images.githubusercontent.com/39266495/208430005-7c2c349e-e5bf-4a0d-973e-d5a7c4ed2749.png)

**Comment by kdtcat** [comment]
I am using now the value divided by 10.000 to get  m³/h which makes most sense for gas consumption.

**Comment by kozmoz** [comment]
Just updated the documentation and added the unit for "report.power_cons". Thanks!
