### ISSUE TITLE
Remote mode not working

### ISSUE THREAD

**Issue by daftz** [kozmoz/atag-one-api#8]
Hi, it seems the remote mode is not working at the moment. When I execute "java -jar atag-one.jar --email xxx --password xxx" it returns "Illegal Argument: null"

I think Atag changed something on their portal. For the last few weeks I've been running Domoticz which also has Atag support but that also stopped working at the end of July (https://www.domoticz.com/forum/viewtopic.php?f=34&t=9286&hilit=atag&start=40#p91820)

**Comment by kozmoz** [comment]
Thank you for reporting. I can confirm that the remote mode is currently broken.

Presumably the HTML of the Atag ONE portal is slightly changed. I will have look at it and will release a new version asap.

**Comment by kozmoz** [comment]
Released version 1.3.3 which contain the fix for remote mode

**Comment by daftz** [comment]
Thanks for the fix!
